export var API_LOADING_STATUS = 'app/API_LOADING_STATUS';
export var ON_CANCEL_ERROR = 'API_CANCEL_ERROR';
export var ON_ERROR = 'ERROR';
export var ON_SUCCESS = 'SUCCESS';
export var ON_FINALLY = 'FINALLY';
export var ON_CANCEL = 'CANCEL';
export var ON_REQUEST = 'REQUEST';
export var ON_LOADING = 'LOADING';
export var ON_UNMOUNT = 'UNMOUNT';
export var ON_TOAST = 'TOAST';
export var ERROR = 'ERROR';
export var SUCCESS = 'SUCCESS';
export var CALL = 'CALL';
export var CANCEL = 'CANCEL';
export var CUSTOM = 'CUSTOM_TASK';
export var commonConstants = {
  ON_CANCEL_ERROR: ON_CANCEL_ERROR,
  ON_ERROR: ON_ERROR,
  ON_SUCCESS: ON_SUCCESS,
  ON_FINALLY: ON_FINALLY,
  ON_CANCEL: ON_CANCEL,
  ON_REQUEST: ON_REQUEST,
  ON_LOADING: ON_LOADING,
  ON_UNMOUNT: ON_UNMOUNT,
  ON_TOAST: ON_TOAST,
  ERROR: ERROR,
  SUCCESS: SUCCESS,
  CALL: CALL,
  CANCEL: CANCEL,
  CUSTOM: CUSTOM
};